# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: rcmdcheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        cases: [ 
          { os: ubuntu-latest, r-version: 4.4.2 },
          { os: ubuntu-latest, r-version: release },
          { os: ubuntu-latest, r-version: devel },
          { os: macos-latest, r-version: 4.4.2 },
          { os: macos-latest, r-version: release },
          { os: windows-latest, r-version: 4.4.2 },
          { os: windows-latest, r-version: release },
          { os: windows-latest, r-version: devel },
        ]
        
    runs-on: ${{ matrix.cases.os }}
    name: ${{ matrix.cases.os }} - ${{ matrix.cases.r-version }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.cases.r-version }}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 3
          extra-packages: >
            any::rcmdcheck
      - name: Check
        run: setwd("src"); rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
